# Site settings
title: Tim Salomonsson
email: tim.echo1911@gmail.com
url: https://tsalomon.github.io
description: "A showcase of my software engineering experience and projects."
keywords: "software,engineer,tim,salomonsson,tim salomonsson,Tim,Salomonsson,CGI,IBM,software projects,software,developer"
skills: "Software Engineer - Information Security Enthusiast - Martial Artist"
meta_author: Salomonsson Tim

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Tim Salomonsson
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:
  - title: stack-overflow
    url:
  - title: bitbucket
    url:
  - title: github
    url: http://github.com/tsalomon

# Postal address (add as many lines as necessary)
address:
  - line: Victoria
  - line: British Columbia, Canada

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-minimal